name: build
on: [push, pull_request]
jobs:
  build-native:
    name: Build native libs
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos
            runner: macos-13
            shell: bash
            platform: macosx-x86_64
            jdkArch: x64
          - os: macos
            runner: macos-13-xlarge
            shell: bash
            platform: macosx-arm64
            jdkArch: aarch64
          - os: linux
            runner: ubuntu-24.04
            shell: bash
            platform: linux-x86_64
          - os: linux
            runner: ubuntu-24.04-arm
            shell: bash
            platform: linux-arm64
    env:
      DETECTED_PLATFORM: ${{ matrix.platform }}
      STAGING: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
        if: matrix.os == 'macos'
        with:
          distribution: 'temurin'
          java-version: '21'
          architecture: ${{ matrix.jdkArch }}
      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
        if: matrix.os == 'macos'
        with:
          xcode-version: 14.1
      - name: Build native binaries
        if: matrix.os == 'macos'
        run: ./build.sh
      - name: Build native binaries in centos container
        if: matrix.os == 'linux'
        uses: docker://ghcr.io/gliwka/centos7-toolchain:main@sha256:e6cf17223408bb4d1314be547d74b23d04bcf6480d2fe23822fb672a52775f76
        with:
          args: '"./build.sh"'
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: build-result-${{ matrix.platform }}
          path: target/staging-deploy
  publish:
    if: contains(github.ref, 'refs/tags/v')
    needs: build-native
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e
        with:
          path: target/staging-deploy
          merge-multiple: true
      - name: Merge multiple local repositories
        run: ./merge-artifacts.sh
      - uses: jreleaser/release-action@f69e545b05f149483cecb2fb81866247992694b8
        with:
          arguments: deploy
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.SIGN_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.SIGN_KEY_PASS }}
