name: build
on: push
jobs:
  build-native:
    name: Build native libs
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        arch: [x86_64]
        include:
          - os: windows-latest
            shell: msys2 {0}
          - os: macos-latest
            shell: bash
          #- os: ubuntu-latest
          # shell: bash
    env:
      OS_ARCH: ${{ matrix.os }}-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: msys2/setup-msys2@v2
        if: matrix.os == 'windows-latest'
        with:
          install: base-devel gcc
          path-type: inherit
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Cache native binaries
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            target/lib
            target/include
          key: ${{ runner.os }}-${{ runner.os }}-${{ hashFiles('build.sh') }}
      - name: Build native binaries
        if: steps.cache.outputs.cache-hit != 'true'
        run: bash build.sh
      - name: Publish package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}