name: build
on: [push, pull_request]
jobs:
  build-native:
    name: Build native libs
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos
            runner: macos-13
            shell: bash
            platform: macosx-x86_64
            jdkArch: x64
          - os: macos
            runner: macos-13-xlarge
            shell: bash
            platform: macosx-arm64
            jdkArch: aarch64
          - os: linux
            runner: ubuntu-latest
            shell: bash
            platform: linux-x86_64
          - os: linux
            runner: buildjet-4vcpu-ubuntu-2204-arm
            shell: bash
            platform: linux-arm64
    env:
      DETECTED_PLATFORM: ${{ matrix.platform }}
      STAGING: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        if: matrix.os == 'macos'
        with:
          distribution: 'temurin'
          java-version: '21'
          architecture: ${{ matrix.jdkArch }}
      - uses: maxim-lobanov/setup-xcode@v1
        if: matrix.os == 'macos'
        with:
          xcode-version: 14.1
      - name: Set signing keys and credentials
        if: startsWith(github.ref, 'refs/tags/v') == true
        run: |
          echo "SIGN_KEY<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.SIGN_KEY }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "SIGN_KEY_PASS=${{ secrets.SIGN_KEY_PASS }}" >> $GITHUB_ENV
          echo "CENTRAL_TOKEN_USERNAME=${{ secrets.CENTRAL_TOKEN_USERNAME }}" >> $GITHUB_ENV
          echo "CENTRAL_TOKEN_PASSWORD=${{ secrets.CENTRAL_TOKEN_PASSWORD }}" >> $GITHUB_ENV
      - name: Build native binaries
        if: matrix.os == 'macos' && startsWith(github.ref, 'refs/tags/v') == true
        run: ./build.sh deploy
      - name: Build native binaries
        if: matrix.os == 'macos' && startsWith(github.ref, 'refs/tags/v') != true
        run: ./build.sh
      - name: Build native binaries in centos container
        if: matrix.os == 'linux' && startsWith(github.ref, 'refs/tags/v') == true
        uses: docker://ghcr.io/gliwka/centos7-toolchain:main@sha256:e6cf17223408bb4d1314be547d74b23d04bcf6480d2fe23822fb672a52775f76
        with:
          args: '"./build.sh deploy"'
      - name: Build native binaries in centos container
        if: matrix.os == 'linux' && startsWith(github.ref, 'refs/tags/v') != true
        uses: docker://ghcr.io/gliwka/centos7-toolchain:main@sha256:e6cf17223408bb4d1314be547d74b23d04bcf6480d2fe23822fb672a52775f76
        with:
          args: '"./build.sh"'
